---
- name: Create top-level NextFlow directory
  file:
    path: "{{ nextflow_root }}"
    state: directory

- name: Install each Nextflow version
  include_tasks: install_version.yml
  vars:
    nf_version: "{{ item }}"
    nf_version_plugins: "{{ nextflow_plugins_root }}"
    nf_version_dest: "{{ nextflow_root }}/{{ item.version }}"
    nf_version_download_url: "https://github.com/nextflow-io/nextflow/releases/download/v{{ item.version }}/nextflow"
  loop: "{{ nextflow_versions }}"
  loop_control:
    loop_var: item
  tags: nextflow_versions

- name: Deploy Nextflow version-selector wrapper
  template:
    src: "nextflow_wrapper.sh.j2"
    dest: "{{ nextflow_dest }}/nextflow"
    mode: u=rwx,g=rx,o=rx

- name: Add NextFlow to $PATH
  lineinfile:
    dest: "{{ ngi_pipeline_conf }}/{{ bash_env_common_script }}"
    line: "export PATH={{ nextflow_dest }}:$PATH"
    backup: no

- name: Download Nextflow plugins
  command: "./nextflow plugin install {{ item.name }}@{{ item.version }}"
  environment: "{{ nextflow_local_env }}"
  with_items: "{{ nextflow_plugins }}"
  args:
    chdir: "{{ nextflow_dest }}"
  tags: plugins

- name: Create miarka config
  template:
    src: "nextflow_miarka_site.config.j2"
    dest: "{{ ngi_pipeline_conf }}/nextflow_miarka_{{ site }}.config"

# Change target to {{ ngi_rnaseq_dest }} when using module system
# NXF_WORK is omitted, which puts them under current directory
- name: Add Nextflow module vars to sourceme
  lineinfile:
    dest: "{{ ngi_pipeline_conf }}/{{ bash_env_common_script }}"
    line: "{{ item }}"
    backup: no
  with_items:
    - export NXF_LAUNCHER="{{ nextflow_env.NXF_LAUNCHER }}"
    - export NXF_OPTS='{{ nextflow_env.NXF_OPTS }}'
    # Path to java to be used for nextflow
    - export NXF_JAVA_HOME={{ nextflow_env.NXF_JAVA_HOME }}
    - export NXF_SINGULARITY_HOME_MOUNT={{ nextflow_env.NXF_SINGULARITY_HOME_MOUNT }}
    - export NXF_PLUGINS_DIR={{ nextflow_plugins_root }}
    - export NXF_HOME={{ nextflow_env.NXF_HOME }}
    - export NXF_OFFLINE='true'

- name: Store nextflow version in deployment
  lineinfile:
    dest: "{{ deployed_tool_versions }}"
    line: "Nextflow: {{ nextflow_version_tag }}"
